title: Phastats
description: Advanced FASTQ Quality Analysis Tool
url: "https://your-username.github.io"
baseurl: "/phastats"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social and contact information
author:
  name: Your Name
  email: your.email@example.com
  
github:
  repository_url: https://github.com/your-username/phastats

# Navigation
navigation:
  - name: Home
    url: /
  - name: Getting Started
    url: /getting-started
  - name: API Reference
    url: /api-reference
  - name: Examples
    url: /examples
  - name: GitHub
    url: https://github.com/your-username/phastats 